---
python_transforms:
  - name: device_config_transform
    class_name: DeviceConfigTransform
    file_path: "device_config.py"

queries:
  - name: device_config_query
    file_path: "device_config.gql"
